/**
 * Flight Deck Fixture Builder
 *
 * Materializes a fully populated Garura target repository at
 * `/tmp/mdb-flight-deck-fixtures` (override via FLIGHT_DECK_FIXTURE_DIR) so
 * the user-testing validators can exercise the Flight Deck with real epic
 * branches, real product artifacts, and real STM evidence.
 *
 * The script is idempotent — it deletes and re-creates the fixture directory
 * on every run so repeated invocations always produce the same state.
 *
 * Layout produced:
 *
 *   /tmp/mdb-flight-deck-fixtures/
 *     .git/                                 ← initialised, main branch, commits
 *     README.md                             ← content committed on main
 *     .garura/
 *       core/config.yaml                    ← points at fixture paths
 *       product/
 *         product.yaml, features.yaml,
 *         architecture.yaml, tech.yaml,
 *         roadmap.yaml, scenarios.yaml, plan.yaml
 *       project/issues/
 *         E1/
 *           play-prepare-epic.yaml          ← play history
 *           play-implement-epic.yaml
 *           quality-check.yaml              ← status: fail → Needs Attention
 *           validation.yaml
 *         E2/
 *           play-prepare-epic.yaml
 *           play-implement-epic.yaml
 *
 * Branches:
 *   main             — baseline, two commits (initial + product artifacts)
 *   feat/e1-auth     — 2 commits ahead of main (implementation work on E1)
 *   feat/e2-billing  — 1 commit ahead of main
 *   feat/e3-dashboard — 0 commits ahead of main
 *
 * Usage:
 *   cd core/engine && npx tsx scripts/create-flight-deck-fixtures.ts
 *
 * Then point the dev server at it:
 *   GARURA_TARGET_REPO=/tmp/mdb-flight-deck-fixtures PORT=3200 pnpm dev
 *   curl http://localhost:3200/api/flight-deck
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = process.env.FLIGHT_DECK_FIXTURE_DIR ?? '/tmp/mdb-flight-deck-fixtures';
const ENGINE_DIR = path.resolve(SCRIPT_DIR, '..');
const REPO_ROOT = path.resolve(ENGINE_DIR, '..', '..'); // core/engine → repo root
const ARTIFACT_SOURCES = [
  // name on disk              → absolute source path
  ['product.yaml', path.join(ENGINE_DIR, 'test-fixtures/.garura/product/product.yaml')],
  ['features.yaml', path.join(ENGINE_DIR, 'test-fixtures/.garura/product/features.yaml')],
  ['architecture.yaml', path.join(ENGINE_DIR, 'test-fixtures/artifacts/architecture.yaml')],
  ['tech.yaml', path.join(ENGINE_DIR, 'test-fixtures/artifacts/tech.yaml')],
  ['roadmap.yaml', path.join(ENGINE_DIR, 'test-fixtures/.garura/product/roadmap.yaml')],
  ['scenarios.yaml', path.join(ENGINE_DIR, 'test-fixtures/.garura/product/scenarios.yaml')],
  ['plan.yaml', path.join(ENGINE_DIR, 'test-fixtures/.garura/product/plan.yaml')],
] as const;

// Deterministic commit metadata — fixtures should be reproducible.
const GIT_USER_NAME = 'garura-fixtures';
const GIT_USER_EMAIL = 'garura-fixtures@example.com';

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function log(msg: string): void {
  // eslint-disable-next-line no-console
  console.log(`[flight-deck-fixtures] ${msg}`);
}

function run(cmd: string, args: readonly string[], cwd: string): void {
  execFileSync(cmd, args, {
    cwd,
    stdio: 'pipe',
    env: {
      ...process.env,
      // Use our deterministic identity regardless of the host's git config.
      GIT_AUTHOR_NAME: GIT_USER_NAME,
      GIT_AUTHOR_EMAIL: GIT_USER_EMAIL,
      GIT_COMMITTER_NAME: GIT_USER_NAME,
      GIT_COMMITTER_EMAIL: GIT_USER_EMAIL,
    },
  });
}

function git(cwd: string, ...args: string[]): void {
  run('git', args, cwd);
}

function writeFile(relativePath: string, contents: string, cwd: string): void {
  const fullPath = path.join(cwd, relativePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, contents, 'utf-8');
}

function copyFile(sourceAbs: string, destRelative: string, cwd: string): void {
  const destAbs = path.join(cwd, destRelative);
  fs.mkdirSync(path.dirname(destAbs), { recursive: true });
  fs.copyFileSync(sourceAbs, destAbs);
}

// ---------------------------------------------------------------------------
// Artifact content helpers
// ---------------------------------------------------------------------------

const CONFIG_YAML = `# Flight Deck fixture configuration for Garura user-testing
# Generated by core/engine/scripts/create-flight-deck-fixtures.ts — do not edit by hand.
project:
  name: TaskFlow
  type: Flight Deck Fixture

# repo.path is relative so the engine resolves it against
# GARURA_TARGET_REPO (set to this fixture directory when starting pnpm dev).
repo:
  path: .

stm:
  base-path: .garura/project/issues/

product:
  base-path: .garura/product/

components:
  skills: ./core/components/skills/
  agents: ./core/components/agents/
`;

const README_MD = `# MDB Flight Deck Fixture Repository

This repository is generated by \`core/engine/scripts/create-flight-deck-fixtures.ts\`.
It is disposable — every run deletes and recreates it. Do not commit changes here.

Point the Garura engine at this directory:

\`\`\`sh
GARURA_TARGET_REPO=/tmp/mdb-flight-deck-fixtures PORT=3200 pnpm dev
\`\`\`
`;

// --- STM evidence ----------------------------------------------------------

const e1PrepareEpicPlayHistory = `# STM play history entry — E1 prepare-epic run
play: play-prepare-epic
status: completed
timestamp: "2026-04-10T09:15:00Z"
durationSeconds: 42
summary: "Prepared epic with locked tech design and scoped scenarios"
artifact_references:
  - type: tech
    id: tech.yaml
`;

const e1ImplementEpicPlayHistory = `# STM play history entry — E1 implement-epic run
play: implement-epic
status: completed
timestamp: "2026-04-15T11:30:00Z"
durationSeconds: 310
summary: "Implemented OAuth login via Google"
artifact_references:
  - type: feature
    id: F1
`;

// Failing quality check on E1 — this is what surfaces E1 in Needs Attention.
const e1QualityCheck = `# STM quality-check evidence — E1 (failing)
play: play-quality-check
status: fail
timestamp: "2026-04-16T08:05:00Z"
issues:
  - "#142 flaky session-timeout test"
  - "#145 token refresh regression"
summary: "2 failing checks surfaced during implementation"
`;

const e1ValidationResult = `# STM validation evidence — E1
status: passed
timestamp: "2026-04-15T12:00:00Z"
scenarios_passed: 5
scenarios_failed: 0
`;

const e2PrepareEpicPlayHistory = `# STM play history entry — E2 prepare-epic run
play: play-prepare-epic
status: completed
timestamp: "2026-04-12T10:00:00Z"
durationSeconds: 55
summary: "Prepared billing epic — tech spec locked"
`;

const e2ImplementEpicPlayHistory = `# STM play history entry — E2 implement-epic run
play: implement-epic
status: completed
timestamp: "2026-04-16T13:20:00Z"
durationSeconds: 280
summary: "Initial billing webhook scaffolding"
`;

// ---------------------------------------------------------------------------
// Build steps
// ---------------------------------------------------------------------------

function resetFixtureDir(): void {
  if (fs.existsSync(FIXTURE_DIR)) {
    log(`removing existing ${FIXTURE_DIR}`);
    fs.rmSync(FIXTURE_DIR, { recursive: true, force: true });
  }
  fs.mkdirSync(FIXTURE_DIR, { recursive: true });
}

function initGitRepo(): void {
  log('initialising git repository on branch main');
  // `-b main` ensures the initial branch is `main` regardless of host
  // init.defaultBranch config. Supported on git ≥ 2.28.
  git(FIXTURE_DIR, 'init', '-b', 'main');
  git(FIXTURE_DIR, 'config', 'user.name', GIT_USER_NAME);
  git(FIXTURE_DIR, 'config', 'user.email', GIT_USER_EMAIL);
  // Explicitly disable GPG signing so host config doesn't block automated commits.
  git(FIXTURE_DIR, 'config', 'commit.gpgsign', 'false');
}

function writeConfigAndReadme(): void {
  writeFile('.garura/core/config.yaml', CONFIG_YAML, FIXTURE_DIR);
  writeFile('README.md', README_MD, FIXTURE_DIR);
}

function writeProductArtifacts(): void {
  log('copying product artifacts into .garura/product/');
  for (const [filename, sourcePath] of ARTIFACT_SOURCES) {
    if (!fs.existsSync(sourcePath)) {
      throw new Error(`Missing source artifact: ${sourcePath}`);
    }
    copyFile(sourcePath, path.join('.garura/product', filename), FIXTURE_DIR);
  }
}

function writeStmEvidence(): void {
  log('writing STM evidence for E1 and E2');
  writeFile(
    '.garura/project/issues/E1/play-prepare-epic.yaml',
    e1PrepareEpicPlayHistory,
    FIXTURE_DIR,
  );
  writeFile(
    '.garura/project/issues/E1/play-implement-epic.yaml',
    e1ImplementEpicPlayHistory,
    FIXTURE_DIR,
  );
  writeFile('.garura/project/issues/E1/quality-check.yaml', e1QualityCheck, FIXTURE_DIR);
  writeFile('.garura/project/issues/E1/validation.yaml', e1ValidationResult, FIXTURE_DIR);
  writeFile(
    '.garura/project/issues/E2/play-prepare-epic.yaml',
    e2PrepareEpicPlayHistory,
    FIXTURE_DIR,
  );
  writeFile(
    '.garura/project/issues/E2/play-implement-epic.yaml',
    e2ImplementEpicPlayHistory,
    FIXTURE_DIR,
  );
}

function commitAll(message: string, dateIso: string): void {
  git(FIXTURE_DIR, 'add', '-A');
  // Use deterministic commit dates so the fixture is reproducible.
  execFileSync('git', ['commit', '-m', message, '--allow-empty', '--date', dateIso], {
    cwd: FIXTURE_DIR,
    stdio: 'pipe',
    env: {
      ...process.env,
      GIT_AUTHOR_NAME: GIT_USER_NAME,
      GIT_AUTHOR_EMAIL: GIT_USER_EMAIL,
      GIT_AUTHOR_DATE: dateIso,
      GIT_COMMITTER_NAME: GIT_USER_NAME,
      GIT_COMMITTER_EMAIL: GIT_USER_EMAIL,
      GIT_COMMITTER_DATE: dateIso,
    },
  });
}

function createMainCommits(): void {
  log('creating initial commits on main');
  // Initial commit: README + config only — a realistic "empty" baseline.
  writeFile('README.md', README_MD, FIXTURE_DIR);
  writeFile('.garura/core/config.yaml', CONFIG_YAML, FIXTURE_DIR);
  commitAll('chore: initial fixture commit', '2026-04-01T10:00:00Z');

  // Second commit: product artifacts (shared by all epics).
  writeProductArtifacts();
  writeStmEvidence();
  commitAll('chore: seed product artifacts and STM evidence', '2026-04-05T10:00:00Z');
}

function createEpicBranch(
  branchName: string,
  commitMessages: readonly string[],
  baseDateIso: string,
): void {
  log(`creating branch ${branchName} with ${commitMessages.length} commits`);
  // Branch from current main HEAD.
  git(FIXTURE_DIR, 'checkout', '-b', branchName, 'main');
  // Advance the date for each commit so commit ordering is deterministic.
  const base = Date.parse(baseDateIso);
  commitMessages.forEach((msg, i) => {
    const commitDate = new Date(base + i * 3600_000).toISOString();
    // Touch a branch-scoped file so each commit has non-empty content.
    const branchFile = path.join('work', branchName.replace(/\//g, '__'), `step-${i + 1}.md`);
    writeFile(
      branchFile,
      `# ${branchName} — step ${i + 1}\n\n${msg}\n\nTimestamp: ${commitDate}\n`,
      FIXTURE_DIR,
    );
    commitAll(msg, commitDate);
  });
  git(FIXTURE_DIR, 'checkout', 'main');
}

function createEpicBranches(): void {
  // E1 — 2 commits ahead, Needs Attention (via failed quality-check STM)
  createEpicBranch(
    'feat/e1-auth',
    ['feat(auth): scaffold OAuth middleware', 'feat(auth): add token refresh regression tests'],
    '2026-04-15T10:00:00Z',
  );

  // E2 — 1 commit ahead, Implementation stage on Track
  createEpicBranch(
    'feat/e2-billing',
    ['feat(billing): initial webhook handler scaffolding'],
    '2026-04-16T13:00:00Z',
  );

  // E3 — 0 commits ahead, Preparing stage (tech.yaml present but no new work)
  log('creating branch feat/e3-dashboard at main (0 commits ahead)');
  git(FIXTURE_DIR, 'checkout', '-b', 'feat/e3-dashboard', 'main');
  git(FIXTURE_DIR, 'checkout', 'main');
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

function main(): void {
  log(`fixture target: ${FIXTURE_DIR}`);
  log(`repo root:      ${REPO_ROOT}`);

  resetFixtureDir();
  initGitRepo();
  writeConfigAndReadme();
  createMainCommits();
  createEpicBranches();

  log('branches:');
  const branches = execFileSync('git', ['branch', '-a'], { cwd: FIXTURE_DIR, encoding: 'utf-8' });
  process.stdout.write(branches);

  log('fixture build complete. Point the engine at it with:');
  log(`  GARURA_TARGET_REPO=${FIXTURE_DIR} PORT=3200 pnpm dev`);
}

main();
